// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package sqlc

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1::int AS one
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var one int32
	err := row.Scan(&one)
	return one, err
}
