// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GroceryAisle struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	SortGroup    int32              `json:"sort_group"`
	SortOrder    int32              `json:"sort_order"`
	NumericValue pgtype.Int4        `json:"numeric_value"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
}

type Item struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	StoreUrl  pgtype.Text        `json:"store_url"`
	AisleID   pgtype.UUID        `json:"aisle_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
}

type MealPlanEntry struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	PlanDate  pgtype.Date        `json:"plan_date"`
	RecipeID  pgtype.UUID        `json:"recipe_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
}

type PersonalAccessToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy  pgtype.UUID        `json:"updated_by"`
}

type Recipe struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	Servings         int32              `json:"servings"`
	PrepTimeMinutes  int32              `json:"prep_time_minutes"`
	TotalTimeMinutes int32              `json:"total_time_minutes"`
	SourceUrl        pgtype.Text        `json:"source_url"`
	Notes            pgtype.Text        `json:"notes"`
	RecipeBookID     pgtype.UUID        `json:"recipe_book_id"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy        pgtype.UUID        `json:"updated_by"`
}

type RecipeBook struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
}

type RecipeIngredient struct {
	ID           pgtype.UUID        `json:"id"`
	RecipeID     pgtype.UUID        `json:"recipe_id"`
	Position     int32              `json:"position"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	QuantityText pgtype.Text        `json:"quantity_text"`
	Unit         pgtype.Text        `json:"unit"`
	Prep         pgtype.Text        `json:"prep"`
	Notes        pgtype.Text        `json:"notes"`
	OriginalText pgtype.Text        `json:"original_text"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
	ItemID       pgtype.UUID        `json:"item_id"`
}

type RecipeStep struct {
	ID          pgtype.UUID        `json:"id"`
	RecipeID    pgtype.UUID        `json:"recipe_id"`
	StepNumber  int32              `json:"step_number"`
	Instruction string             `json:"instruction"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
}

type RecipeTag struct {
	RecipeID  pgtype.UUID        `json:"recipe_id"`
	TagID     pgtype.UUID        `json:"tag_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy  pgtype.UUID        `json:"updated_by"`
}

type ShoppingList struct {
	ID        pgtype.UUID        `json:"id"`
	ListDate  pgtype.Date        `json:"list_date"`
	Name      string             `json:"name"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
}

type ShoppingListItem struct {
	ID             pgtype.UUID        `json:"id"`
	ShoppingListID pgtype.UUID        `json:"shopping_list_id"`
	ItemID         pgtype.UUID        `json:"item_id"`
	Unit           pgtype.Text        `json:"unit"`
	Quantity       pgtype.Numeric     `json:"quantity"`
	QuantityText   pgtype.Text        `json:"quantity_text"`
	IsPurchased    bool               `json:"is_purchased"`
	PurchasedAt    pgtype.Timestamptz `json:"purchased_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  pgtype.Text        `json:"display_name"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
}
