// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipe_books.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecipeBook = `-- name: CreateRecipeBook :one
INSERT INTO recipe_books (
  name,
  created_by,
  updated_by
) VALUES (
  $1, $2, $3
)
RETURNING id, name, created_at, created_by, updated_at, updated_by
`

type CreateRecipeBookParams struct {
	Name      string      `json:"name"`
	CreatedBy pgtype.UUID `json:"created_by"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) CreateRecipeBook(ctx context.Context, arg CreateRecipeBookParams) (RecipeBook, error) {
	row := q.db.QueryRow(ctx, createRecipeBook, arg.Name, arg.CreatedBy, arg.UpdatedBy)
	var i RecipeBook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteRecipeBookByID = `-- name: DeleteRecipeBookByID :execrows
DELETE FROM recipe_books
WHERE id = $1
`

func (q *Queries) DeleteRecipeBookByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecipeBookByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listRecipeBooks = `-- name: ListRecipeBooks :many
SELECT id, name, created_at, created_by, updated_at, updated_by
FROM recipe_books
ORDER BY name ASC
`

func (q *Queries) ListRecipeBooks(ctx context.Context) ([]RecipeBook, error) {
	rows, err := q.db.Query(ctx, listRecipeBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeBook{}
	for rows.Next() {
		var i RecipeBook
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipeBookByID = `-- name: UpdateRecipeBookByID :one
UPDATE recipe_books
SET name = $2, updated_at = now(), updated_by = $3
WHERE id = $1
RETURNING id, name, created_at, created_by, updated_at, updated_by
`

type UpdateRecipeBookByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateRecipeBookByID(ctx context.Context, arg UpdateRecipeBookByIDParams) (RecipeBook, error) {
	row := q.db.QueryRow(ctx, updateRecipeBookByID, arg.ID, arg.Name, arg.UpdatedBy)
	var i RecipeBook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
