// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (
  name,
  created_by,
  updated_by
) VALUES (
  $1, $2, $3
)
RETURNING id, name, created_at, created_by, updated_at, updated_by
`

type CreateTagParams struct {
	Name      string      `json:"name"`
	CreatedBy pgtype.UUID `json:"created_by"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.CreatedBy, arg.UpdatedBy)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteTagByID = `-- name: DeleteTagByID :execrows
DELETE FROM tags
WHERE id = $1
`

func (q *Queries) DeleteTagByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTagByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, created_at, created_by, updated_at, updated_by
FROM tags
ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTagByID = `-- name: UpdateTagByID :one
UPDATE tags
SET name = $2, updated_at = now(), updated_by = $3
WHERE id = $1
RETURNING id, name, created_at, created_by, updated_at, updated_by
`

type UpdateTagByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateTagByID(ctx context.Context, arg UpdateTagByIDParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTagByID, arg.ID, arg.Name, arg.UpdatedBy)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
