// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :one
INSERT INTO personal_access_tokens (
  user_id,
  name,
  token_hash,
  last_used_at,
  expires_at,
  created_by,
  updated_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, name, token_hash, last_used_at, expires_at, created_at, created_by, updated_at, updated_by
`

type CreateTokenParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	UpdatedBy  pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteTokenByIDForUser = `-- name: DeleteTokenByIDForUser :execrows
DELETE FROM personal_access_tokens
WHERE id = $1 AND user_id = $2
`

type DeleteTokenByIDForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTokenByIDForUser(ctx context.Context, arg DeleteTokenByIDForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTokenByIDForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTokenUserByHash = `-- name: GetTokenUserByHash :one
SELECT
  t.id as token_id,
  t.user_id as token_user_id,
  t.expires_at as token_expires_at,
  u.id as user_id,
  u.username as username,
  u.display_name as display_name,
  u.is_active as is_active
FROM personal_access_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1
`

type GetTokenUserByHashRow struct {
	TokenID        pgtype.UUID        `json:"token_id"`
	TokenUserID    pgtype.UUID        `json:"token_user_id"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	UserID         pgtype.UUID        `json:"user_id"`
	Username       string             `json:"username"`
	DisplayName    pgtype.Text        `json:"display_name"`
	IsActive       bool               `json:"is_active"`
}

func (q *Queries) GetTokenUserByHash(ctx context.Context, tokenHash string) (GetTokenUserByHashRow, error) {
	row := q.db.QueryRow(ctx, getTokenUserByHash, tokenHash)
	var i GetTokenUserByHashRow
	err := row.Scan(
		&i.TokenID,
		&i.TokenUserID,
		&i.TokenExpiresAt,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.IsActive,
	)
	return i, err
}

const listTokensByUser = `-- name: ListTokensByUser :many
SELECT id, user_id, name, token_hash, last_used_at, expires_at, created_at, created_by, updated_at, updated_by
FROM personal_access_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTokensByUser(ctx context.Context, userID pgtype.UUID) ([]PersonalAccessToken, error) {
	rows, err := q.db.Query(ctx, listTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonalAccessToken{}
	for rows.Next() {
		var i PersonalAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTokenLastUsed = `-- name: TouchTokenLastUsed :exec
UPDATE personal_access_tokens
SET last_used_at = now(), updated_at = now(), updated_by = $2
WHERE id = $1
`

type TouchTokenLastUsedParams struct {
	ID        pgtype.UUID `json:"id"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) TouchTokenLastUsed(ctx context.Context, arg TouchTokenLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchTokenLastUsed, arg.ID, arg.UpdatedBy)
	return err
}
