// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::int AS count FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id,
  username,
  password_hash,
  display_name,
  is_active,
  created_by,
  updated_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, username, password_hash, display_name, is_active, created_at, created_by, updated_at, updated_by
`

type CreateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  pgtype.Text `json:"display_name"`
	IsActive     bool        `json:"is_active"`
	CreatedBy    pgtype.UUID `json:"created_by"`
	UpdatedBy    pgtype.UUID `json:"updated_by"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, display_name, is_active, created_at, created_by, updated_at, updated_by FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, display_name, is_active, created_at, created_by, updated_at, updated_by FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, display_name, is_active, created_at, created_by, updated_at, updated_by FROM users
ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.DisplayName,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users
SET is_active = $2, updated_at = now(), updated_by = $3
WHERE id = $1
RETURNING id, username, password_hash, display_name, is_active, created_at, created_by, updated_at, updated_by
`

type SetUserActiveParams struct {
	ID        pgtype.UUID `json:"id"`
	IsActive  bool        `json:"is_active"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.ID, arg.IsActive, arg.UpdatedBy)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
