run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosec:
    excludes:
      - G114 # recover + panic is fine for simple CLI apps
  govet:
    enable:
      - shadow
  revive:
    rules:
      - name: exported
      - name: unreachable-code
  staticcheck:
    checks:
      - all
      - "-SA1019"

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - ineffassign
    - revive
    - gofmt
    - goimports
    - goconst
    - gosec
    - gocritic
    - misspell
    - prealloc
    - unconvert
    - unparam
    - whitespace
