-- Code generated by cmd/schema-gen; DO NOT EDIT.
-- Source: Goose migrations in backend/migrations/

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE users (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	username citext NOT NULL UNIQUE,
	password_hash text NOT NULL,
	display_name text NULL,
	is_active boolean NOT NULL DEFAULT true,
	created_at timestamptz NOT NULL DEFAULT now(),
	created_by uuid NOT NULL REFERENCES users (id),
	updated_at timestamptz NOT NULL DEFAULT now(),
	updated_by uuid NOT NULL REFERENCES users (id)
);

CREATE TABLE recipe_books (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	name citext NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	created_by uuid NOT NULL REFERENCES users (id),
	updated_at timestamptz NOT NULL DEFAULT now(),
	updated_by uuid NOT NULL REFERENCES users (id),
	CONSTRAINT recipe_books_name_unique UNIQUE (name)
);

CREATE TABLE tags (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	name citext NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	created_by uuid NOT NULL REFERENCES users (id),
	updated_at timestamptz NOT NULL DEFAULT now(),
	updated_by uuid NOT NULL REFERENCES users (id),
	CONSTRAINT tags_name_unique UNIQUE (name)
);

CREATE TABLE recipes (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	title text NOT NULL,
	servings int NOT NULL CONSTRAINT recipes_servings_positive_chk CHECK (servings > 0),
	prep_time_minutes int NOT NULL CONSTRAINT recipes_prep_time_nonneg_chk CHECK (prep_time_minutes >= 0),
	total_time_minutes int NOT NULL CONSTRAINT recipes_total_time_nonneg_chk CHECK (total_time_minutes >= 0),
	source_url text NULL,
	notes text NULL,
	recipe_book_id uuid NULL REFERENCES recipe_books (id),
	deleted_at timestamptz NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	created_by uuid NOT NULL REFERENCES users (id),
	updated_at timestamptz NOT NULL DEFAULT now(),
	updated_by uuid NOT NULL REFERENCES users (id)
);

CREATE INDEX recipes_updated_at_idx ON recipes (updated_at DESC);
CREATE INDEX recipes_deleted_at_idx ON recipes (deleted_at);
CREATE INDEX recipes_title_trgm_idx ON recipes USING gin (title gin_trgm_ops);

CREATE TABLE recipe_ingredients (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	recipe_id uuid NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
	position int NOT NULL CONSTRAINT recipe_ingredients_position_positive_chk CHECK (position >= 1),
	quantity numeric NULL,
	quantity_text text NULL,
	unit text NULL,
	item text NOT NULL,
	prep text NULL,
	notes text NULL,
	original_text text NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	created_by uuid NOT NULL REFERENCES users (id),
	updated_at timestamptz NOT NULL DEFAULT now(),
	updated_by uuid NOT NULL REFERENCES users (id)
);

CREATE INDEX recipe_ingredients_recipe_id_position_idx ON recipe_ingredients (recipe_id, position);

CREATE TABLE recipe_steps (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	recipe_id uuid NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
	step_number int NOT NULL CONSTRAINT recipe_steps_step_number_positive_chk CHECK (step_number >= 1),
	instruction text NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	created_by uuid NOT NULL REFERENCES users (id),
	updated_at timestamptz NOT NULL DEFAULT now(),
	updated_by uuid NOT NULL REFERENCES users (id),
	CONSTRAINT recipe_steps_recipe_id_step_number_unique UNIQUE (recipe_id, step_number)
);

CREATE INDEX recipe_steps_recipe_id_step_number_idx ON recipe_steps (recipe_id, step_number);

CREATE TABLE recipe_tags (
	recipe_id uuid NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
	tag_id uuid NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
	created_at timestamptz NOT NULL DEFAULT now(),
	created_by uuid NOT NULL REFERENCES users (id),
	updated_at timestamptz NOT NULL DEFAULT now(),
	updated_by uuid NOT NULL REFERENCES users (id),
	PRIMARY KEY (recipe_id, tag_id)
);

CREATE INDEX recipe_tags_tag_id_idx ON recipe_tags (tag_id);

CREATE TABLE personal_access_tokens (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	name text NOT NULL,
	token_hash text NOT NULL,
	last_used_at timestamptz NULL,
	expires_at timestamptz NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	created_by uuid NOT NULL REFERENCES users (id),
	updated_at timestamptz NOT NULL DEFAULT now(),
	updated_by uuid NOT NULL REFERENCES users (id),
	CONSTRAINT personal_access_tokens_token_hash_unique UNIQUE (token_hash)
);

CREATE INDEX personal_access_tokens_user_id_idx ON personal_access_tokens (user_id);
CREATE INDEX personal_access_tokens_expires_at_idx ON personal_access_tokens (expires_at);

CREATE TABLE sessions (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	token_hash bytea NOT NULL,
	expires_at timestamptz NOT NULL,
	last_seen_at timestamptz NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	created_by uuid NOT NULL REFERENCES users (id),
	updated_at timestamptz NOT NULL DEFAULT now(),
	updated_by uuid NOT NULL REFERENCES users (id),
	CONSTRAINT sessions_token_hash_unique UNIQUE (token_hash)
);

CREATE INDEX sessions_user_id_idx ON sessions (user_id);
CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);

CREATE TABLE meal_plan_entries (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	plan_date date NOT NULL,
	recipe_id uuid NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
	created_at timestamptz NOT NULL DEFAULT now(),
	created_by uuid NOT NULL REFERENCES users (id),
	updated_at timestamptz NOT NULL DEFAULT now(),
	updated_by uuid NOT NULL REFERENCES users (id),
	CONSTRAINT meal_plan_entries_user_date_recipe_unique UNIQUE (user_id, plan_date, recipe_id)
);

CREATE INDEX meal_plan_entries_user_date_idx ON meal_plan_entries (user_id, plan_date);

CREATE TABLE grocery_aisles (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	name citext NOT NULL,
	sort_group int NOT NULL CONSTRAINT grocery_aisles_sort_group_chk CHECK (sort_group IN (0, 1, 2)),
	sort_order int NOT NULL,
	numeric_value int NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	created_by uuid NOT NULL REFERENCES users (id),
	updated_at timestamptz NOT NULL DEFAULT now(),
	updated_by uuid NOT NULL REFERENCES users (id),
	CONSTRAINT grocery_aisles_name_unique UNIQUE (name)
);

CREATE INDEX grocery_aisles_sort_idx ON grocery_aisles (sort_group, sort_order, name);

CREATE TABLE items (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	name citext NOT NULL,
	store_url text NULL,
	aisle_id uuid NULL REFERENCES grocery_aisles (id) ON DELETE SET NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	created_by uuid NOT NULL REFERENCES users (id),
	updated_at timestamptz NOT NULL DEFAULT now(),
	updated_by uuid NOT NULL REFERENCES users (id),
	CONSTRAINT items_name_unique UNIQUE (name)
);

CREATE INDEX items_name_trgm_idx ON items USING gin (name gin_trgm_ops);
CREATE INDEX items_aisle_id_idx ON items (aisle_id);

CREATE TABLE shopping_lists (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	list_date date NOT NULL,
	name text NOT NULL,
	notes text NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	created_by uuid NOT NULL REFERENCES users (id),
	updated_at timestamptz NOT NULL DEFAULT now(),
	updated_by uuid NOT NULL REFERENCES users (id)
);

CREATE INDEX shopping_lists_date_idx ON shopping_lists (list_date);

CREATE TABLE shopping_list_items (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	shopping_list_id uuid NOT NULL REFERENCES shopping_lists (id) ON DELETE CASCADE,
	item_id uuid NOT NULL REFERENCES items (id),
	unit text NULL,
	quantity numeric NULL,
	quantity_text text NULL,
	is_purchased boolean NOT NULL DEFAULT false,
	purchased_at timestamptz NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	created_by uuid NOT NULL REFERENCES users (id),
	updated_at timestamptz NOT NULL DEFAULT now(),
	updated_by uuid NOT NULL REFERENCES users (id),
	CONSTRAINT shopping_list_items_list_item_unit_unique UNIQUE (shopping_list_id, item_id, unit)
);

CREATE INDEX shopping_list_items_list_id_idx ON shopping_list_items (shopping_list_id);
CREATE INDEX shopping_list_items_item_id_idx ON shopping_list_items (item_id);

ALTER TABLE recipe_ingredients
	ADD COLUMN item_id uuid;

INSERT INTO items (name, created_by, updated_by)
SELECT
	item,
	MIN(created_by) AS created_by,
	MIN(updated_by) AS updated_by
FROM recipe_ingredients
GROUP BY item
ON CONFLICT (name) DO NOTHING;

UPDATE recipe_ingredients ri
SET item_id = i.id
FROM items i
WHERE i.name = ri.item;

ALTER TABLE recipe_ingredients
	ALTER COLUMN item_id SET NOT NULL;

ALTER TABLE recipe_ingredients
	ADD CONSTRAINT recipe_ingredients_item_id_fkey FOREIGN KEY (item_id) REFERENCES items (id);

CREATE INDEX recipe_ingredients_item_id_idx ON recipe_ingredients (item_id);

ALTER TABLE recipe_ingredients
	DROP COLUMN item;
